### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by tstraub89** [SynerClust/SynerClust#14]
I get this error when starting to run SynerClust. It then fails and exits.
`Traceback (most recent call last):
  File "/gsap/garage-bacterial/Users/Tim/SynerClust/bin/synerclust.py", line 197, in <module>
    main()
  File "/gsap/garage-bacterial/Users/Tim/SynerClust/bin/synerclust.py", line 107, in main
    myTree.rootTree(root_edge)
  File "/gsap/garage-bacterial/Users/Tim/SynerClust/bin/TreeLib.py", line 193, in rootTree
    re_weight = (self.tree.edge[root_edge[0]][root_edge[1]]['weight']) / 2.0
AttributeError: 'Graph' object has no attribute 'edge'`

**Comment by tstraub89** [comment]
I believe I have traced this error to a version of NetworkX package that is not supported. Perhaps we could add a warning that the package in your environment is not supported, rather than this cryptic error.
